// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sapapplicationlogs.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import sapapplicationlogs.Settings;
import sapapplicationlogs.SubscriberConfigurer;
import com.mendix.logging.LogLevel;

public class RegisterSubscriber extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String SapLogLevel;

	public RegisterSubscriber(IContext context, java.lang.String SapLogLevel)
	{
		super(context);
		this.SapLogLevel = SapLogLevel;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		// if service is not available, skip
		if (!Settings.isServiceAvailable()) {
			return true;
		}
		
		LogLevel logLevel;

		switch (SapLogLevel.toLowerCase()) {
		case "critical":
			logLevel = com.mendix.logging.LogLevel.CRITICAL;
			break;
		case "debug":
			logLevel = com.mendix.logging.LogLevel.DEBUG;
			break;
		case "error":
			logLevel = com.mendix.logging.LogLevel.ERROR;
			break;
		case "info":
			logLevel = com.mendix.logging.LogLevel.INFO;
			break;
		case "trace":
			logLevel = com.mendix.logging.LogLevel.TRACE;
			break;
		case "warning":
			logLevel = com.mendix.logging.LogLevel.WARNING;
			break;
		default:
			logLevel = com.mendix.logging.LogLevel.INFO;
			break;
		}

		new Thread(() -> {
			// register json subscriber
			SubscriberConfigurer.registerJsonSubscriber(logLevel);
			// sleep to prevent race condition
			try {
				Thread.sleep(5000);
			} catch (InterruptedException e) {
				return;
			}
			// silence logger created by cf buildpack
			SubscriberConfigurer.silenceFileSubscriber();
		}).start();
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RegisterSubscriber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
