// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package odataquerybuilder.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import odataquerybuilder.proxies.OptionType;
import odataquerybuilder.proxies.Order;
import odataquerybuilder.proxies.QueryOption;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * It is used to sort the results based on OData properties.
 */
public class AddOrderBy extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __OData;
	private odataquerybuilder.proxies.OData OData;
	private odataquerybuilder.proxies.Order SortOrder;
	private java.lang.String ODataField;

	public AddOrderBy(IContext context, IMendixObject OData, java.lang.String SortOrder, java.lang.String ODataField)
	{
		super(context);
		this.__OData = OData;
		this.SortOrder = SortOrder == null ? null : odataquerybuilder.proxies.Order.valueOf(SortOrder);
		this.ODataField = ODataField;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.OData = this.__OData == null ? null : odataquerybuilder.proxies.OData.initialize(getContext(), __OData);

		// BEGIN USER CODE
		QueryOption orderby = new QueryOption(this.getContext());
		orderby.setOptionType(OptionType.orderby);
		orderby.setQueryParam_OData(OData);
		String value = ODataField;
		if(SortOrder!= null){
			if(SortOrder == Order.Ascending)
				value = value + " asc";
			else{
				value = value + " desc";
			}
		}
		orderby.setValue(value);
		orderby.commit();
		orderby.setOrder(OData.getNextOrderNumber());
		OData.setNextOrderNumber(OData.getNextOrderNumber()+1);
		OData.commit();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddOrderBy";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
