// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package odataquerybuilder.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import odataquerybuilder.proxies.OptionType;
import odataquerybuilder.proxies.QueryOption;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * You can select which attributes and associations to return by specifying the $select query option. For example: VariableNames = Name
 */
public class Select extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __OData;
	private odataquerybuilder.proxies.OData OData;
	private java.lang.String VariableNames;

	public Select(IContext context, IMendixObject OData, java.lang.String VariableNames)
	{
		super(context);
		this.__OData = OData;
		this.VariableNames = VariableNames;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.OData = this.__OData == null ? null : odataquerybuilder.proxies.OData.initialize(getContext(), __OData);

		// BEGIN USER CODE
		QueryOption select = new QueryOption(this.getContext());
		select.setOptionType(OptionType.select);
		select.setValue(VariableNames);
		select.setQueryParam_OData(OData);
		select.commit();
		select.setOrder(OData.getNextOrderNumber());
		OData.setNextOrderNumber(OData.getNextOrderNumber()+1);
		OData.commit();
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Select";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
