// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package odataquerybuilder.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import odataquerybuilder.proxies.OData;

/**
 * Returns an OData object based on the provided initial parameters.
 * This object is then used by other actions to add further parameters to the query, if required.
 */
public class Start extends CustomJavaAction<IMendixObject>
{
	private java.lang.String Location;
	private java.lang.String CollectionName;
	private odataquerybuilder.proxies.Format Format;
	private java.lang.Boolean v3FunctionStyle;

	public Start(IContext context, java.lang.String Location, java.lang.String CollectionName, java.lang.String Format, java.lang.Boolean v3FunctionStyle)
	{
		super(context);
		this.Location = Location;
		this.CollectionName = CollectionName;
		this.Format = Format == null ? null : odataquerybuilder.proxies.Format.valueOf(Format);
		this.v3FunctionStyle = v3FunctionStyle;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		OData odata = new OData(this.getContext());
		odata.setFormat(Format);
		odata.setLocation(Location);
		odata.setV3FunctionStyle(v3FunctionStyle);		
		odata.setCollectionName(CollectionName);
		return odata.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Start";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
